export interface School {
  name: string;
  state: string;
  latitude: number;
  longitude: number;
  city: string;
  country: string;
}

export const schools: School[] = [
  {
    name: 'Massachusetts Institute of Technology',
    state: 'Massachusetts',
    latitude: 42.359006,
    longitude: -71.093539,
    city: 'Cambridge',
    country: 'United States',
  },
  {
    name: 'Stanford University',
    state: 'California',
    latitude: 37.43137,
    longitude: -122.168924,
    city: 'Stanford',
    country: 'United States',
  },
  {
    name: 'University of California, Berkeley',
    state: 'California',
    latitude: 37.869236,
    longitude: -122.258393,
    city: 'Berkeley',
    country: 'United States',
  },
  {
    name: 'Princeton University',
    state: 'New Jersey',
    latitude: 40.349855,
    longitude: -74.659119,
    city: 'Princeton',
    country: 'United States',
  },
  {
    name: 'Columbia University',
    state: 'New York',
    latitude: 40.806515,
    longitude: -73.961288,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'University of California, Los Angeles',
    state: 'California',
    latitude: 34.073903,
    longitude: -118.437855,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'Williams College',
    state: 'Massachusetts',
    latitude: 42.712389,
    longitude: -73.208078,
    city: 'Williamstown',
    country: 'United States',
  },
  {
    name: 'Yale University',
    state: 'Connecticut',
    latitude: 41.314042,
    longitude: -72.923425,
    city: 'New Haven',
    country: 'United States',
  },
  {
    name: 'Duke University',
    state: 'North Carolina',
    latitude: 36.001389,
    longitude: -78.940277,
    city: 'Durham',
    country: 'United States',
  },
  {
    name: 'University of Pennsylvania',
    state: 'Pennsylvania',
    latitude: 39.95227,
    longitude: -75.162369,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'Northwestern University',
    state: 'Illinois',
    latitude: 42.04965,
    longitude: -87.67874,
    city: 'Evanston',
    country: 'United States',
  },
  {
    name: 'Rice University',
    state: 'Texas',
    latitude: 29.76045,
    longitude: -95.369784,
    city: 'Houston',
    country: 'United States',
  },
  {
    name: 'Vanderbilt University',
    state: 'Tennessee',
    latitude: 36.150323,
    longitude: -86.801456,
    city: 'Nashville',
    country: 'United States',
  },
  {
    name: 'Dartmouth College',
    state: 'New Hampshire',
    latitude: 43.700465,
    longitude: -72.289499,
    city: 'Hanover',
    country: 'United States',
  },
  {
    name: 'Harvard University',
    state: 'Massachusetts',
    latitude: 42.374699,
    longitude: -71.112957,
    city: 'Cambridge',
    country: 'United States',
  },
  {
    name: 'Cornell University',
    state: 'New York',
    latitude: 42.453558,
    longitude: -76.48451,
    city: 'Ithaca',
    country: 'United States',
  },
  {
    name: 'University of California, San Diego',
    state: 'California',
    latitude: 32.87271,
    longitude: -117.237726,
    city: 'La Jolla',
    country: 'United States',
  },
  {
    name: 'Johns Hopkins University',
    state: 'Maryland',
    latitude: 39.290555,
    longitude: -76.609604,
    city: 'Baltimore',
    country: 'United States',
  },
  {
    name: 'Brown University',
    state: 'Rhode Island',
    latitude: 41.858184,
    longitude: -71.449747,
    city: 'Providence',
    country: 'United States',
  },
  {
    name: 'University of Chicago',
    state: 'Illinois',
    latitude: 41.790203,
    longitude: -87.601242,
    city: 'Chicago',
    country: 'United States',
  },
  {
    name: 'University of Southern California',
    state: 'California',
    latitude: 34.019231,
    longitude: -118.282761,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'Georgetown University',
    state: 'District of Columbia',
    latitude: 38.899101,
    longitude: -77.028999,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'University of California, Davis',
    state: 'California',
    latitude: 38.540631,
    longitude: -121.747976,
    city: 'Davis',
    country: 'United States',
  },
  {
    name: 'Amherst College',
    state: 'Massachusetts',
    latitude: 42.370772,
    longitude: -72.533204,
    city: 'Amherst',
    country: 'United States',
  },
  {
    name: 'University of Michigan, Ann Arbor',
    state: 'Michigan',
    latitude: 42.281875,
    longitude: -83.748479,
    city: 'Ann Arbor',
    country: 'United States',
  },
  {
    name: 'University of Florida',
    state: 'Florida',
    latitude: 29.65195,
    longitude: -82.323184,
    city: 'Gainesville',
    country: 'United States',
  },
  {
    name: 'Washington University in St. Louis',
    state: 'Missouri',
    latitude: 38.647812,
    longitude: -90.301291,
    city: 'St. Louis',
    country: 'United States',
  },
  {
    name: 'University of North Carolina, Chapel Hill',
    state: 'North Carolina',
    latitude: 35.914639,
    longitude: -79.056619,
    city: 'Chapel Hill',
    country: 'United States',
  },
  {
    name: 'University of Virginia',
    state: 'Virginia',
    latitude: 38.078711,
    longitude: -78.581033,
    city: 'Charlottesville',
    country: 'United States',
  },
  {
    name: 'University of California, Irvine',
    state: 'California',
    latitude: 33.686887,
    longitude: -117.825348,
    city: 'Irvine',
    country: 'United States',
  },
  {
    name: 'Emory University',
    state: 'Georgia',
    latitude: 33.789755,
    longitude: -84.325741,
    city: 'Atlanta',
    country: 'United States',
  },
  {
    name: 'Tufts University',
    state: 'Massachusetts',
    latitude: 42.419815,
    longitude: -71.108759,
    city: 'Medford',
    country: 'United States',
  },
  {
    name: 'University of Washington, Seattle',
    state: 'Washington',
    latitude: 47.656216,
    longitude: -122.31312,
    city: 'Seattle',
    country: 'United States',
  },
  {
    name: 'University of Illinois, Urbana-Champaign',
    state: 'Illinois',
    latitude: 40.109132,
    longitude: -88.230238,
    city: 'Champaign',
    country: 'United States',
  },
  {
    name: 'Georgia Institute of Technology',
    state: 'Georgia',
    latitude: 33.771317,
    longitude: -84.394396,
    city: 'Atlanta',
    country: 'United States',
  },
  {
    name: 'University of Notre Dame',
    state: 'Indiana',
    latitude: 41.700748,
    longitude: -86.239189,
    city: 'Notre Dame',
    country: 'United States',
  },
  {
    name: 'Wellesley College',
    state: 'Massachusetts',
    latitude: 42.295986,
    longitude: -71.300245,
    city: 'Wellesley',
    country: 'United States',
  },
  {
    name: 'Swarthmore College',
    state: 'Pennsylvania',
    latitude: 39.90655,
    longitude: -75.35216,
    city: 'Swarthmore',
    country: 'United States',
  },
  {
    name: 'University of California, Santa Barbara',
    state: 'California',
    latitude: 34.41566,
    longitude: -119.846464,
    city: 'Santa Barbara',
    country: 'United States',
  },
  {
    name: 'University of Maryland, College Park',
    state: 'Maryland',
    latitude: 38.980725,
    longitude: -76.937269,
    city: 'College Park',
    country: 'United States',
  },
  {
    name: 'William & Mary',
    state: 'Virginia',
    latitude: 37.275609,
    longitude: -76.709724,
    city: 'Williamsburg',
    country: 'United States',
  },
  {
    name: 'Boston College',
    state: 'Massachusetts',
    latitude: 42.326095,
    longitude: -71.164564,
    city: 'Chestnut Hill',
    country: 'United States',
  },
  {
    name: 'University of Texas, Austin',
    state: 'Texas',
    latitude: 30.14628,
    longitude: -97.827889,
    city: 'Austin',
    country: 'United States',
  },
  {
    name: 'Colgate University',
    state: 'New York',
    latitude: 42.821191,
    longitude: -75.536415,
    city: 'Hamilton',
    country: 'United States',
  },
  {
    name: 'California Institute of Technology',
    state: 'California',
    latitude: 34.135911,
    longitude: -118.125942,
    city: 'Pasadena',
    country: 'United States',
  },
  {
    name: 'Carnegie Mellon University',
    state: 'Pennsylvania',
    latitude: 40.444639,
    longitude: -79.943067,
    city: 'Pittsburgh',
    country: 'United States',
  },
  {
    name: 'Claremont McKenna College',
    state: 'California',
    latitude: 34.102632,
    longitude: -117.706769,
    city: 'Claremont',
    country: 'United States',
  },
  {
    name: 'Bowdoin College',
    state: 'Maine',
    latitude: 43.906764,
    longitude: -69.963975,
    city: 'Brunswick',
    country: 'United States',
  },
  {
    name: 'University of Wisconsin, Madison',
    state: 'Wisconsin',
    latitude: 43.07295,
    longitude: -89.386694,
    city: 'Madison',
    country: 'United States',
  },
  {
    name: 'Wake Forest University',
    state: 'North Carolina',
    latitude: 36.136824,
    longitude: -80.27403,
    city: 'Winston-Salem',
    country: 'United States',
  },
];

export const disciplines = [
  'Accounting',
  'Anthropology',
  'Architecture',
  'Art History',
  'Biology',
  'Business Administration',
  'Chemistry',
  'Civil Engineering',
  'Communication',
  'Computer Engineering',
  'Computer Science',
  'Creative Writing',
  'Criminal Justice',
  'Data Science',
  'Dentistry',
  'Design',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English Literature',
  'Environmental Science',
  'Finance',
  'Fine Arts',
  'History',
  'International Relations',
  'Journalism',
  'Law',
  'Management',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Music',
  'Nursing',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Statistics',
  'Theology',
  'Urban Planning',
];

export const programTypes = [
  "Bachelor's",
  "Master's",
  'Ph.D.',
  'J.D.', // Law degree
  'M.D.', // Medical degree
  'M.B.A.', // Business degree
  'Ed.D.', // Doctor of Education
  'M.P.H.', // Master of Public Health
  'Professional Certificate',
  'Postdoctoral Fellowship',
  'Residency Program',
  "Associate's Degree",
  'Trade School / Vocational',
  'Gap Year',
  'Undecided',
  'Other',
];
