export interface School {
  name: string;
  state: string;
  latitude: number;
  longitude: number;
  city: string;
  country: string;
}

export const schools: School[] = [
  {
    name: 'Massachusetts Institute of Technology',
    state: 'Massachusetts',
    latitude: 42.359006,
    longitude: -71.093539,
    city: 'Cambridge',
    country: 'United States',
  },
  {
    name: 'Stanford University',
    state: 'California',
    latitude: 37.43137,
    longitude: -122.168924,
    city: 'Stanford',
    country: 'United States',
  },
  {
    name: 'University of California, Berkeley',
    state: 'California',
    latitude: 37.869236,
    longitude: -122.258393,
    city: 'Berkeley',
    country: 'United States',
  },
  {
    name: 'Princeton University',
    state: 'New Jersey',
    latitude: 40.349855,
    longitude: -74.659119,
    city: 'Princeton',
    country: 'United States',
  },
  {
    name: 'Columbia University',
    state: 'New York',
    latitude: 40.806515,
    longitude: -73.961288,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'University of California, Los Angeles',
    state: 'California',
    latitude: 34.073903,
    longitude: -118.437855,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'Williams College',
    state: 'Massachusetts',
    latitude: 42.712389,
    longitude: -73.208078,
    city: 'Williamstown',
    country: 'United States',
  },
  {
    name: 'Yale University',
    state: 'Connecticut',
    latitude: 41.314042,
    longitude: -72.923425,
    city: 'New Haven',
    country: 'United States',
  },
  {
    name: 'Duke University',
    state: 'North Carolina',
    latitude: 36.001389,
    longitude: -78.940277,
    city: 'Durham',
    country: 'United States',
  },
  {
    name: 'University of Pennsylvania',
    state: 'Pennsylvania',
    latitude: 39.95227,
    longitude: -75.162369,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'Northwestern University',
    state: 'Illinois',
    latitude: 42.04965,
    longitude: -87.67874,
    city: 'Evanston',
    country: 'United States',
  },
  {
    name: 'Rice University',
    state: 'Texas',
    latitude: 29.76045,
    longitude: -95.369784,
    city: 'Houston',
    country: 'United States',
  },
  {
    name: 'Vanderbilt University',
    state: 'Tennessee',
    latitude: 36.150323,
    longitude: -86.801456,
    city: 'Nashville',
    country: 'United States',
  },
  {
    name: 'Dartmouth College',
    state: 'New Hampshire',
    latitude: 43.700465,
    longitude: -72.289499,
    city: 'Hanover',
    country: 'United States',
  },
  {
    name: 'Harvard University',
    state: 'Massachusetts',
    latitude: 42.374699,
    longitude: -71.112957,
    city: 'Cambridge',
    country: 'United States',
  },
  {
    name: 'Cornell University',
    state: 'New York',
    latitude: 42.453558,
    longitude: -76.48451,
    city: 'Ithaca',
    country: 'United States',
  },
  {
    name: 'University of California, San Diego',
    state: 'California',
    latitude: 32.87271,
    longitude: -117.237726,
    city: 'La Jolla',
    country: 'United States',
  },
  {
    name: 'Johns Hopkins University',
    state: 'Maryland',
    latitude: 39.290555,
    longitude: -76.609604,
    city: 'Baltimore',
    country: 'United States',
  },
  {
    name: 'Brown University',
    state: 'Rhode Island',
    latitude: 41.858184,
    longitude: -71.449747,
    city: 'Providence',
    country: 'United States',
  },
  {
    name: 'University of Chicago',
    state: 'Illinois',
    latitude: 41.790203,
    longitude: -87.601242,
    city: 'Chicago',
    country: 'United States',
  },
  {
    name: 'University of Southern California',
    state: 'California',
    latitude: 34.019231,
    longitude: -118.282761,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'Georgetown University',
    state: 'District of Columbia',
    latitude: 38.899101,
    longitude: -77.028999,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'University of California, Davis',
    state: 'California',
    latitude: 38.540631,
    longitude: -121.747976,
    city: 'Davis',
    country: 'United States',
  },
  {
    name: 'Amherst College',
    state: 'Massachusetts',
    latitude: 42.370772,
    longitude: -72.533204,
    city: 'Amherst',
    country: 'United States',
  },
  {
    name: 'University of Michigan, Ann Arbor',
    state: 'Michigan',
    latitude: 42.281875,
    longitude: -83.748479,
    city: 'Ann Arbor',
    country: 'United States',
  },
  {
    name: 'University of Florida',
    state: 'Florida',
    latitude: 29.65195,
    longitude: -82.323184,
    city: 'Gainesville',
    country: 'United States',
  },
  {
    name: 'Washington University in St. Louis',
    state: 'Missouri',
    latitude: 38.647812,
    longitude: -90.301291,
    city: 'St. Louis',
    country: 'United States',
  },
  {
    name: 'University of North Carolina, Chapel Hill',
    state: 'North Carolina',
    latitude: 35.914639,
    longitude: -79.056619,
    city: 'Chapel Hill',
    country: 'United States',
  },
  {
    name: 'University of Virginia',
    state: 'Virginia',
    latitude: 38.078711,
    longitude: -78.581033,
    city: 'Charlottesville',
    country: 'United States',
  },
  {
    name: 'University of California, Irvine',
    state: 'California',
    latitude: 33.686887,
    longitude: -117.825348,
    city: 'Irvine',
    country: 'United States',
  },
  {
    name: 'Emory University',
    state: 'Georgia',
    latitude: 33.789755,
    longitude: -84.325741,
    city: 'Atlanta',
    country: 'United States',
  },
  {
    name: 'Tufts University',
    state: 'Massachusetts',
    latitude: 42.419815,
    longitude: -71.108759,
    city: 'Medford',
    country: 'United States',
  },
  {
    name: 'University of Washington, Seattle',
    state: 'Washington',
    latitude: 47.656216,
    longitude: -122.31312,
    city: 'Seattle',
    country: 'United States',
  },
  {
    name: 'University of Illinois, Urbana-Champaign',
    state: 'Illinois',
    latitude: 40.109132,
    longitude: -88.230238,
    city: 'Champaign',
    country: 'United States',
  },
  {
    name: 'Georgia Institute of Technology',
    state: 'Georgia',
    latitude: 33.771317,
    longitude: -84.394396,
    city: 'Atlanta',
    country: 'United States',
  },
  {
    name: 'University of Notre Dame',
    state: 'Indiana',
    latitude: 41.700748,
    longitude: -86.239189,
    city: 'Notre Dame',
    country: 'United States',
  },
  {
    name: 'Wellesley College',
    state: 'Massachusetts',
    latitude: 42.295986,
    longitude: -71.300245,
    city: 'Wellesley',
    country: 'United States',
  },
  {
    name: 'Swarthmore College',
    state: 'Pennsylvania',
    latitude: 39.90655,
    longitude: -75.35216,
    city: 'Swarthmore',
    country: 'United States',
  },
  {
    name: 'University of California, Santa Barbara',
    state: 'California',
    latitude: 34.41566,
    longitude: -119.846464,
    city: 'Santa Barbara',
    country: 'United States',
  },
  {
    name: 'University of Maryland, College Park',
    state: 'Maryland',
    latitude: 38.980725,
    longitude: -76.937269,
    city: 'College Park',
    country: 'United States',
  },
  {
    name: 'William & Mary',
    state: 'Virginia',
    latitude: 37.275609,
    longitude: -76.709724,
    city: 'Williamsburg',
    country: 'United States',
  },
  {
    name: 'Boston College',
    state: 'Massachusetts',
    latitude: 42.326095,
    longitude: -71.164564,
    city: 'Chestnut Hill',
    country: 'United States',
  },
  {
    name: 'University of Texas, Austin',
    state: 'Texas',
    latitude: 30.14628,
    longitude: -97.827889,
    city: 'Austin',
    country: 'United States',
  },
  {
    name: 'Colgate University',
    state: 'New York',
    latitude: 42.821191,
    longitude: -75.536415,
    city: 'Hamilton',
    country: 'United States',
  },
  {
    name: 'California Institute of Technology',
    state: 'California',
    latitude: 34.135911,
    longitude: -118.125942,
    city: 'Pasadena',
    country: 'United States',
  },
  {
    name: 'Carnegie Mellon University',
    state: 'Pennsylvania',
    latitude: 40.444639,
    longitude: -79.943067,
    city: 'Pittsburgh',
    country: 'United States',
  },
  {
    name: 'Claremont McKenna College',
    state: 'California',
    latitude: 34.102632,
    longitude: -117.706769,
    city: 'Claremont',
    country: 'United States',
  },
  {
    name: 'Bowdoin College',
    state: 'Maine',
    latitude: 43.906764,
    longitude: -69.963975,
    city: 'Brunswick',
    country: 'United States',
  },
  {
    name: 'University of Wisconsin, Madison',
    state: 'Wisconsin',
    latitude: 43.07295,
    longitude: -89.386694,
    city: 'Madison',
    country: 'United States',
  },
  {
    name: 'Wake Forest University',
    state: 'North Carolina',
    latitude: 36.136824,
    longitude: -80.27403,
    city: 'Winston-Salem',
    country: 'United States',
  },
  {
    name: 'Wesleyan University',
    state: 'Connecticut',
    latitude: 41.556899,
    longitude: -72.657422,
    city: 'Middletown',
    country: 'United States',
  },
  {
    name: 'Texas A&M University, College Station',
    state: 'Texas',
    latitude: 30.55207,
    longitude: -96.361139,
    city: 'College Station',
    country: 'United States',
  },
  {
    name: 'Hamilton College',
    state: 'New York',
    latitude: 43.050328,
    longitude: -75.404593,
    city: 'Clinton',
    country: 'United States',
  },
  {
    name: 'Boston University',
    state: 'Massachusetts',
    latitude: 42.350173,
    longitude: -71.098846,
    city: 'Boston',
    country: 'United States',
  },
  {
    name: 'Middlebury College',
    state: 'Vermont',
    latitude: 44.014999,
    longitude: -73.167117,
    city: 'Middlebury',
    country: 'United States',
  },
  {
    name: 'Santa Clara University',
    state: 'California',
    latitude: 37.351709,
    longitude: -121.937018,
    city: 'Santa Clara',
    country: 'United States',
  },
  {
    name: 'Brigham Young University',
    state: 'Utah',
    latitude: 40.250622,
    longitude: -111.656874,
    city: 'Provo',
    country: 'United States',
  },
  {
    name: 'Purdue University',
    state: 'Indiana',
    latitude: 40.429296,
    longitude: -86.914454,
    city: 'West Lafayette',
    country: 'United States',
  },
  {
    name: 'Washington and Lee University',
    state: 'Virginia',
    latitude: 37.786248,
    longitude: -79.443623,
    city: 'Lexington',
    country: 'United States',
  },
  {
    name: 'New York University',
    state: 'New York',
    latitude: 40.729844,
    longitude: -73.997189,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'George Washington University',
    state: 'District of Columbia',
    latitude: 38.903034,
    longitude: -76.973533,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'Trinity College (CT)',
    state: 'Connecticut',
    latitude: 41.750228,
    longitude: -72.693036,
    city: 'Hartford',
    country: 'United States',
  },
  {
    name: 'San Diego State University',
    state: 'California',
    latitude: 32.772283,
    longitude: -117.071913,
    city: 'San Diego',
    country: 'United States',
  },
  {
    name: 'University of Georgia',
    state: 'Georgia',
    latitude: 33.925215,
    longitude: -83.393519,
    city: 'Athens',
    country: 'United States',
  },
  {
    name: 'Binghamton University, SUNY',
    state: 'New York',
    latitude: 42.098687,
    longitude: -75.911271,
    city: 'Binghamton',
    country: 'United States',
  },
  {
    name: 'CUNY, Baruch College',
    state: 'New York',
    latitude: 40.740725,
    longitude: -73.983628,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Florida State University',
    state: 'Florida',
    latitude: 30.38673,
    longitude: -84.210779,
    city: 'Tallahassee',
    country: 'United States',
  },
  {
    name: 'University of Minnesota, Twin Cities',
    state: 'Minnesota',
    latitude: 44.97598,
    longitude: -93.233867,
    city: 'Minneapolis',
    country: 'United States',
  },
  {
    name: 'Davidson College',
    state: 'North Carolina',
    latitude: 35.497841,
    longitude: -80.84922,
    city: 'Davidson',
    country: 'United States',
  },
  {
    name: 'North Carolina State University, Raleigh',
    state: 'North Carolina',
    latitude: 35.78551,
    longitude: -78.642669,
    city: 'Raleigh',
    country: 'United States',
  },
  {
    name: 'Barnard College',
    state: 'New York',
    latitude: 40.809471,
    longitude: -73.962972,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'University of Richmond',
    state: 'Virginia',
    latitude: 37.573622,
    longitude: -77.539491,
    city: 'Richmond',
    country: 'United States',
  },
  {
    name: 'Vassar College',
    state: 'New York',
    latitude: 41.68544,
    longitude: -73.897898,
    city: 'Poughkeepsie',
    country: 'United States',
  },
  {
    name: 'University of Connecticut',
    state: 'Connecticut',
    latitude: 41.808457,
    longitude: -72.250089,
    city: 'Storrs',
    country: 'United States',
  },
  {
    name: 'New Jersey Institute of Technology',
    state: 'New Jersey',
    latitude: 40.743752,
    longitude: -74.18264,
    city: 'Newark',
    country: 'United States',
  },
  {
    name: 'California State University, Fullerton',
    state: 'California',
    latitude: 33.870325,
    longitude: -117.929104,
    city: 'Fullerton',
    country: 'United States',
  },
  {
    name: 'Lafayette College',
    state: 'Pennsylvania',
    latitude: 40.691195,
    longitude: -75.209829,
    city: 'Easton',
    country: 'United States',
  },
  {
    name: 'University of Miami (FL)',
    state: 'Florida',
    latitude: 25.749238,
    longitude: -80.262949,
    city: 'Coral Gables',
    country: 'United States',
  },
  {
    name: 'Northeastern University',
    state: 'Massachusetts',
    latitude: 42.340252,
    longitude: -71.08899,
    city: 'Boston',
    country: 'United States',
  },
  {
    name: 'California State University, Long Beach',
    state: 'California',
    latitude: 33.782235,
    longitude: -118.122401,
    city: 'Long Beach',
    country: 'United States',
  },
  {
    name: 'Michigan State University',
    state: 'Michigan',
    latitude: 42.730519,
    longitude: -84.47978,
    city: 'East Lansing',
    country: 'United States',
  },
  {
    name: 'Virginia Tech',
    state: 'Virginia',
    latitude: 37.226263,
    longitude: -80.410584,
    city: 'Blacksburg',
    country: 'United States',
  },
  {
    name: 'Southern Methodist University',
    state: 'Texas',
    latitude: 32.844423,
    longitude: -96.785697,
    city: 'Dallas',
    country: 'United States',
  },
  {
    name: 'University of California, Riverside',
    state: 'California',
    latitude: 33.975652,
    longitude: -117.331148,
    city: 'Riverside',
    country: 'United States',
  },
  {
    name: 'Pomona College',
    state: 'California',
    latitude: 34.096849,
    longitude: -117.712684,
    city: 'Claremont',
    country: 'United States',
  },
  {
    name: 'Stony Brook University, SUNY',
    state: 'New York',
    latitude: 40.919163,
    longitude: -73.129583,
    city: 'Stony Brook',
    country: 'United States',
  },
  {
    name: 'University of California, Santa Cruz',
    state: 'California',
    latitude: 36.977109,
    longitude: -122.052279,
    city: 'Santa Cruz',
    country: 'United States',
  },
  {
    name: 'University of Utah',
    state: 'Utah',
    latitude: 40.765448,
    longitude: -111.849786,
    city: 'Salt Lake City',
    country: 'United States',
  },
  {
    name: 'Bucknell University',
    state: 'Pennsylvania',
    latitude: 40.956816,
    longitude: -76.883566,
    city: 'Lewisburg',
    country: 'United States',
  },
  {
    name: 'University at Buffalo',
    state: 'New York',
    latitude: 42.956016,
    longitude: -78.820489,
    city: 'Buffalo',
    country: 'United States',
  },
  {
    name: 'Indiana University, Bloomington',
    state: 'Indiana',
    latitude: 39.168482,
    longitude: -86.516138,
    city: 'Bloomington',
    country: 'United States',
  },
  {
    name: 'Grinnell College',
    state: 'Iowa',
    latitude: 41.749041,
    longitude: -92.720673,
    city: 'Grinnell',
    country: 'United States',
  },
  {
    name: 'Rutgers University',
    state: 'New Jersey',
    latitude: 40.52537,
    longitude: -74.453208,
    city: 'New Brunswick',
    country: 'United States',
  },
  {
    name: 'Villanova University',
    state: 'Pennsylvania',
    latitude: 40.0358,
    longitude: -75.348574,
    city: 'Villanova',
    country: 'United States',
  },
  {
    name: 'Bryn Mawr College',
    state: 'Pennsylvania',
    latitude: 40.024968,
    longitude: -75.318703,
    city: 'Bryn Mawr',
    country: 'United States',
  },
  {
    name: 'Colorado College',
    state: 'Colorado',
    latitude: 38.84655,
    longitude: -104.824202,
    city: 'Colorado Springs',
    country: 'United States',
  },
  {
    name: 'University of Rochester',
    state: 'New York',
    latitude: 43.132968,
    longitude: -77.61986,
    city: 'Rochester',
    country: 'United States',
  },
  {
    name: 'California Polytechnic State University, San Luis Obispo',
    state: 'California',
    latitude: 35.296104,
    longitude: -120.653076,
    city: 'San Luis Obispo',
    country: 'United States',
  },
  {
    name: 'University of Illinois at Chicago',
    state: 'Illinois',
    latitude: 41.88415,
    longitude: -87.632409,
    city: 'Chicago',
    country: 'United States',
  },
  {
    name: 'Loyola Marymount University',
    state: 'California',
    latitude: 33.968304,
    longitude: -118.42214,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'Bates College',
    state: 'Maine',
    latitude: 44.098555,
    longitude: -70.218354,
    city: 'Lewiston',
    country: 'United States',
  },
  {
    name: 'Syracuse University',
    state: 'New York',
    latitude: 43.04999,
    longitude: -76.147389,
    city: 'Syracuse',
    country: 'United States',
  },
  {
    name: 'University of Colorado, Boulder',
    state: 'Colorado',
    latitude: 40.01574,
    longitude: -105.279239,
    city: 'Boulder',
    country: 'United States',
  },
  {
    name: 'Colby College',
    state: 'Maine',
    latitude: 44.560149,
    longitude: -69.659599,
    city: 'Waterville',
    country: 'United States',
  },
  {
    name: 'Haverford College',
    state: 'Pennsylvania',
    latitude: 40.013819,
    longitude: -75.302845,
    city: 'Haverford',
    country: 'United States',
  },
  {
    name: 'Lehigh University',
    state: 'Pennsylvania',
    latitude: 40.607182,
    longitude: -75.378892,
    city: 'Bethlehem',
    country: 'United States',
  },
  {
    name: 'Case Western Reserve University',
    state: 'Ohio',
    latitude: 41.50603,
    longitude: -81.60896,
    city: 'Cleveland',
    country: 'United States',
  },
  {
    name: 'San Jose State University',
    state: 'California',
    latitude: 37.334371,
    longitude: -121.880567,
    city: 'San Jose',
    country: 'United States',
  },
  {
    name: 'University of San Diego',
    state: 'California',
    latitude: 32.771734,
    longitude: -117.184998,
    city: 'San Diego',
    country: 'United States',
  },
  {
    name: 'Babson College',
    state: 'Massachusetts',
    latitude: 42.3015529,
    longitude: -71.266966,
    city: 'Babson Park',
    country: 'United States',
  },
  {
    name: 'University of Houston',
    state: 'Texas',
    latitude: 29.76045,
    longitude: -95.369784,
    city: 'Houston',
    country: 'United States',
  },
  {
    name: 'Brandeis University',
    state: 'Massachusetts',
    latitude: 42.365886,
    longitude: -71.254994,
    city: 'Waltham',
    country: 'United States',
  },
  {
    name: 'Clemson University',
    state: 'South Carolina',
    latitude: 34.676941,
    longitude: -82.83889,
    city: 'Clemson',
    country: 'United States',
  },
  {
    name: 'Harvey Mudd College',
    state: 'California',
    latitude: 34.0961,
    longitude: -117.716404,
    city: 'Claremont',
    country: 'United States',
  },
  {
    name: 'Tulane University',
    state: 'Louisiana',
    latitude: 29.935368,
    longitude: -90.123993,
    city: 'New Orleans',
    country: 'United States',
  },
  {
    name: 'Louisiana State University',
    state: 'Louisiana',
    latitude: 30.443335,
    longitude: -91.186994,
    city: 'Baton Rouge',
    country: 'United States',
  },
  {
    name: 'University of Tennessee, Knoxville',
    state: 'Tennessee',
    latitude: 35.960495,
    longitude: -83.920914,
    city: 'Knoxville',
    country: 'United States',
  },
  {
    name: 'University of South Florida',
    state: 'Florida',
    latitude: 28.054569,
    longitude: -82.412955,
    city: 'Tampa',
    country: 'United States',
  },
  {
    name: 'University of Central Florida',
    state: 'Florida',
    latitude: 28.49394,
    longitude: -81.359699,
    city: 'Orlando',
    country: 'United States',
  },
  {
    name: 'Florida International University',
    state: 'Florida',
    latitude: 25.749064,
    longitude: -80.23745,
    city: 'Miami',
    country: 'United States',
  },
  {
    name: 'University of Texas, Dallas',
    state: 'Texas',
    latitude: 32.978288,
    longitude: -96.748549,
    city: 'Richardson',
    country: 'United States',
  },
  {
    name: 'Skidmore College',
    state: 'New York',
    latitude: 43.095269,
    longitude: -73.779826,
    city: 'Saratoga Springs',
    country: 'United States',
  },
  {
    name: 'Colorado School of Mines',
    state: 'Colorado',
    latitude: 39.75118,
    longitude: -105.222281,
    city: 'Golden',
    country: 'United States',
  },
  {
    name: 'CUNY, The City College of New York',
    state: 'New York',
    latitude: 40.818917,
    longitude: -73.950429,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Arizona State University, Tempe',
    state: 'Arizona',
    latitude: 33.42551,
    longitude: -111.937419,
    city: 'Tempe',
    country: 'United States',
  },
  {
    name: 'Occidental College',
    state: 'California',
    latitude: 34.126222,
    longitude: -118.214263,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'Franklin W Olin College of Engineering',
    state: 'Massachusetts',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Needham',
    country: 'United States',
  },
  {
    name: 'CUNY, Hunter College',
    state: 'New York',
    latitude: 40.768926,
    longitude: -73.965259,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Scripps College',
    state: 'California',
    latitude: 34.103735,
    longitude: -117.711478,
    city: 'Claremont',
    country: 'United States',
  },
  {
    name: 'Yeshiva University',
    state: 'New York',
    latitude: 40.85058,
    longitude: -73.929369,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'University of Arizona',
    state: 'Arizona',
    latitude: 32.221553,
    longitude: -110.969754,
    city: 'Tucson',
    country: 'United States',
  },
  {
    name: 'University of Delaware',
    state: 'Delaware',
    latitude: 39.677597,
    longitude: -75.753559,
    city: 'Newark',
    country: 'United States',
  },
  {
    name: 'American University',
    state: 'District of Columbia',
    latitude: 38.938475,
    longitude: -77.086683,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'College of the Holy Cross',
    state: 'Massachusetts',
    latitude: 42.239597,
    longitude: -71.812679,
    city: 'Worcester',
    country: 'United States',
  },
  {
    name: 'University of Maryland, Baltimore County',
    state: 'Maryland',
    latitude: 39.3401,
    longitude: -76.551689,
    city: 'Baltimore',
    country: 'United States',
  },
  {
    name: 'Auburn University',
    state: 'Alabama',
    latitude: 32.607465,
    longitude: -85.481735,
    city: 'Auburn',
    country: 'United States',
  },
  {
    name: 'University of Iowa',
    state: 'Iowa',
    latitude: 41.662517,
    longitude: -91.536515,
    city: 'Iowa City',
    country: 'United States',
  },
  {
    name: 'Franklin and Marshall College',
    state: 'Pennsylvania',
    latitude: 40.01461,
    longitude: -76.310739,
    city: 'Lancaster',
    country: 'United States',
  },
  {
    name: 'James Madison University',
    state: 'Virginia',
    latitude: 38.451534,
    longitude: -78.869047,
    city: 'Harrisonburg',
    country: 'United States',
  },
  {
    name: 'George Mason University',
    state: 'Virginia',
    latitude: 38.835035,
    longitude: -77.310869,
    city: 'Fairfax',
    country: 'United States',
  },
  {
    name: 'San Francisco State University',
    state: 'California',
    latitude: 37.720808,
    longitude: -122.477234,
    city: 'San Francisco',
    country: 'United States',
  },
  {
    name: 'California State Polytechnic University, Pomona',
    state: 'California',
    latitude: 34.050329,
    longitude: -117.816806,
    city: 'Pomona',
    country: 'United States',
  },
  {
    name: 'Texas Christian University',
    state: 'Texas',
    latitude: 32.74863,
    longitude: -97.329249,
    city: 'Fort Worth',
    country: 'United States',
  },
  {
    name: 'University of Missouri, Columbia',
    state: 'Missouri',
    latitude: 38.944388,
    longitude: -92.329211,
    city: 'Columbia',
    country: 'United States',
  },
  {
    name: 'University of Denver',
    state: 'Colorado',
    latitude: 39.676705,
    longitude: -104.959389,
    city: 'Denver',
    country: 'United States',
  },
  {
    name: 'Smith College',
    state: 'Massachusetts',
    latitude: 42.31979,
    longitude: -72.640426,
    city: 'Northampton',
    country: 'United States',
  },
  {
    name: 'California State University, Los Angeles',
    state: 'California',
    latitude: 34.0795169,
    longitude: -118.1766294,
    city: 'Los Angeles',
    country: 'United States',
  },
  {
    name: 'University of Oklahoma, Norman',
    state: 'Oklahoma',
    latitude: 35.210434,
    longitude: -97.445963,
    city: 'Norman',
    country: 'United States',
  },
  {
    name: 'Carleton College',
    state: 'Minnesota',
    latitude: 44.459801,
    longitude: -93.155545,
    city: 'Northfield',
    country: 'United States',
  },
  {
    name: 'University of Oregon',
    state: 'Oregon',
    latitude: 44.04992,
    longitude: -123.088544,
    city: 'Eugene',
    country: 'United States',
  },
  {
    name: 'Rutgers University, Newark',
    state: 'New Jersey',
    latitude: 40.740476,
    longitude: -74.172669,
    city: 'Newark',
    country: 'United States',
  },
  {
    name: 'Texas Tech University',
    state: 'Texas',
    latitude: 33.59233,
    longitude: -101.855869,
    city: 'Lubbock',
    country: 'United States',
  },
  {
    name: 'University of Washington Bothell',
    state: 'Washington',
    latitude: 47.759,
    longitude: -122.19058,
    city: 'Bothell',
    country: 'United States',
  },
  {
    name: 'Fordham University',
    state: 'New York',
    latitude: 40.825745,
    longitude: -73.923249,
    city: 'Bronx',
    country: 'United States',
  },
  {
    name: 'Cooper Union',
    state: 'New York',
    latitude: 40.728186,
    longitude: -73.991253,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Iowa State University',
    state: 'Iowa',
    latitude: 42.025345,
    longitude: -93.620199,
    city: 'Ames',
    country: 'United States',
  },
  {
    name: 'University of the Pacific (CA)',
    state: 'California',
    latitude: 37.95362,
    longitude: -121.290719,
    city: 'Stockton',
    country: 'United States',
  },
  {
    name: 'Oregon State University',
    state: 'Oregon',
    latitude: 44.564499,
    longitude: -123.281982,
    city: 'Corvallis',
    country: 'United States',
  },
  {
    name: 'Marquette University',
    state: 'Wisconsin',
    latitude: 43.04181,
    longitude: -87.906844,
    city: 'Milwaukee',
    country: 'United States',
  },
  {
    name: 'Rhodes College',
    state: 'Tennessee',
    latitude: 35.152147,
    longitude: -89.992319,
    city: 'Memphis',
    country: 'United States',
  },
  {
    name: 'University of South Carolina',
    state: 'South Carolina',
    latitude: 33.99855,
    longitude: -81.045249,
    city: 'Columbia',
    country: 'United States',
  },
  {
    name: 'Trinity University (TX)',
    state: 'Texas',
    latitude: 29.463276,
    longitude: -98.481143,
    city: 'San Antonio',
    country: 'United States',
  },
  {
    name: 'University of Vermont',
    state: 'Vermont',
    latitude: 44.474524,
    longitude: -73.200614,
    city: 'Burlington',
    country: 'United States',
  },
  {
    name: 'Baylor University',
    state: 'Texas',
    latitude: 31.48673,
    longitude: -97.278939,
    city: 'Waco',
    country: 'United States',
  },
  {
    name: 'University of Kansas',
    state: 'Kansas',
    latitude: 38.956145,
    longitude: -95.260466,
    city: 'Lawrence',
    country: 'United States',
  },
  {
    name: 'California State University, Northridge',
    state: 'California',
    latitude: 34.235511,
    longitude: -118.52864,
    city: 'Northridge',
    country: 'United States',
  },
  {
    name: 'Furman University',
    state: 'South Carolina',
    latitude: 34.925074,
    longitude: -82.433165,
    city: 'Greenville',
    country: 'United States',
  },
  {
    name: 'Drexel University',
    state: 'Pennsylvania',
    latitude: 39.953701,
    longitude: -75.186582,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'Bentley University',
    state: 'Massachusetts',
    latitude: 42.390739,
    longitude: -71.222413,
    city: 'Waltham',
    country: 'United States',
  },
  {
    name: 'California State University, Fresno',
    state: 'California',
    latitude: 36.810521,
    longitude: -119.745229,
    city: 'Fresno',
    country: 'United States',
  },
  {
    name: 'Illinois Institute of Technology',
    state: 'Illinois',
    latitude: 41.834684,
    longitude: -87.626894,
    city: 'Chicago',
    country: 'United States',
  },
  {
    name: 'CUNY, Queens College',
    state: 'New York',
    latitude: 40.736153,
    longitude: -73.814758,
    city: 'Queens',
    country: 'United States',
  },
  {
    name: 'Ohio State University',
    state: 'Ohio',
    latitude: 39.96196,
    longitude: -83.002984,
    city: 'Columbus',
    country: 'United States',
  },
  {
    name: 'Union College (NY)',
    state: 'New York',
    latitude: 42.81226,
    longitude: -73.941026,
    city: 'Schenectady',
    country: 'United States',
  },
  {
    name: 'University of Tulsa',
    state: 'Oklahoma',
    latitude: 36.149583,
    longitude: -95.946129,
    city: 'Tulsa',
    country: 'United States',
  },
  {
    name: 'Kenyon College',
    state: 'Ohio',
    latitude: 40.375937,
    longitude: -82.397924,
    city: 'Gambier',
    country: 'United States',
  },
  {
    name: 'Rensselaer Polytechnic Institute',
    state: 'New York',
    latitude: 42.731366,
    longitude: -73.68396,
    city: 'Troy',
    country: 'United States',
  },
  {
    name: 'Rose-Hulman Institute of Technology',
    state: 'Indiana',
    latitude: 39.466495,
    longitude: -87.413229,
    city: 'Terre Haute',
    country: 'United States',
  },
  {
    name: 'Pepperdine University',
    state: 'California',
    latitude: 34.036175,
    longitude: -118.689574,
    city: 'Malibu',
    country: 'United States',
  },
  {
    name: 'Fashion Institute of Technology',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Denison University',
    state: 'Ohio',
    latitude: 40.069229,
    longitude: -82.520247,
    city: 'Granville',
    country: 'United States',
  },
  {
    name: 'Dickinson College',
    state: 'Pennsylvania',
    latitude: 40.20119,
    longitude: -77.189169,
    city: 'Carlisle',
    country: 'United States',
  },
  {
    name: 'Kalamazoo College',
    state: 'Michigan',
    latitude: 42.290416,
    longitude: -85.601299,
    city: 'Kalamazoo',
    country: 'United States',
  },
  {
    name: 'University of Nevada-Reno',
    state: 'Nevada',
    latitude: 39.54789,
    longitude: -119.821126,
    city: 'Reno',
    country: 'United States',
  },
  {
    name: 'College of New Jersey',
    state: 'New Jersey',
    latitude: 40.271116,
    longitude: -74.783122,
    city: 'Ewing',
    country: 'United States',
  },
  {
    name: 'Elon University',
    state: 'North Carolina',
    latitude: 36.10477,
    longitude: -79.503422,
    city: 'Elon',
    country: 'United States',
  },
  {
    name: 'Pitzer College',
    state: 'California',
    latitude: 34.103376,
    longitude: -117.707094,
    city: 'Claremont',
    country: 'United States',
  },
  {
    name: 'Worcester Polytechnic Institute',
    state: 'Massachusetts',
    latitude: 42.272658,
    longitude: -71.80784,
    city: 'Worcester',
    country: 'United States',
  },
  {
    name: 'University of Arkansas',
    state: 'Arkansas',
    latitude: 36.063205,
    longitude: -94.157914,
    city: 'Fayetteville',
    country: 'United States',
  },
  {
    name: 'University of Portland',
    state: 'Oregon',
    latitude: 45.57463,
    longitude: -122.725002,
    city: 'Portland',
    country: 'United States',
  },
  {
    name: 'Washington State University',
    state: 'Washington',
    latitude: 46.730155,
    longitude: -117.181494,
    city: 'Pullman',
    country: 'United States',
  },
  {
    name: 'University of Dayton',
    state: 'Ohio',
    latitude: 39.740535,
    longitude: -84.180241,
    city: 'Dayton',
    country: 'United States',
  },
  {
    name: 'University of Washington, Tacoma Campus',
    state: 'Washington',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Tacoma',
    country: 'United States',
  },
  {
    name: 'Connecticut College',
    state: 'Connecticut',
    latitude: 41.378681,
    longitude: -72.10371,
    city: 'New London',
    country: 'United States',
  },
  {
    name: 'Creighton University',
    state: 'Nebraska',
    latitude: 41.264826,
    longitude: -95.947074,
    city: 'Omaha',
    country: 'United States',
  },
  {
    name: 'Mount Holyoke College',
    state: 'Massachusetts',
    latitude: 42.256627,
    longitude: -72.57628,
    city: 'South Hadley',
    country: 'United States',
  },
  {
    name: 'University of San Francisco',
    state: 'California',
    latitude: 37.775128,
    longitude: -122.451859,
    city: 'San Francisco',
    country: 'United States',
  },
  {
    name: 'University of Massachusetts, Amherst',
    state: 'Massachusetts',
    latitude: 42.385848,
    longitude: -72.522839,
    city: 'Amherst',
    country: 'United States',
  },
  {
    name: 'Whitman College',
    state: 'Washington',
    latitude: 46.070353,
    longitude: -118.329646,
    city: 'Walla Walla',
    country: 'United States',
  },
  {
    name: 'University of Kentucky',
    state: 'Kentucky',
    latitude: 38.048595,
    longitude: -84.500319,
    city: 'Lexington',
    country: 'United States',
  },
  {
    name: 'DePauw University',
    state: 'Indiana',
    latitude: 39.643995,
    longitude: -86.861129,
    city: 'Greencastle',
    country: 'United States',
  },
  {
    name: 'Macalester College',
    state: 'Minnesota',
    latitude: 44.940082,
    longitude: -93.167996,
    city: 'St. Paul',
    country: 'United States',
  },
  {
    name: 'Saint Louis University',
    state: 'Missouri',
    latitude: 38.634531,
    longitude: -90.233777,
    city: 'St. Louis',
    country: 'United States',
  },
  {
    name: 'CUNY, Brooklyn College',
    state: 'New York',
    latitude: 40.631798,
    longitude: -73.952666,
    city: 'Brooklyn',
    country: 'United States',
  },
  {
    name: 'Temple University',
    state: 'Pennsylvania',
    latitude: 39.95227,
    longitude: -75.162369,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'The Citadel',
    state: 'South Carolina',
    latitude: 32.796892,
    longitude: -79.957841,
    city: 'Charleston',
    country: 'United States',
  },
  {
    name: 'Oberlin College',
    state: 'Ohio',
    latitude: 41.292925,
    longitude: -82.217354,
    city: 'Oberlin',
    country: 'United States',
  },
  {
    name: 'Rhode Island School of Design',
    state: 'Rhode Island',
    latitude: 41.82509,
    longitude: -71.409601,
    city: 'Providence',
    country: 'United States',
  },
  {
    name: 'University of Pittsburgh',
    state: 'Pennsylvania',
    latitude: 40.438335,
    longitude: -79.997459,
    city: 'Pittsburgh',
    country: 'United States',
  },
  {
    name: 'Gettysburg College',
    state: 'Pennsylvania',
    latitude: 39.835319,
    longitude: -77.233389,
    city: 'Gettysburg',
    country: 'United States',
  },
  {
    name: 'California State University, Sacramento',
    state: 'California',
    latitude: 38.567262,
    longitude: -121.427322,
    city: 'Sacramento',
    country: 'United States',
  },
  {
    name: 'California State University, Chico',
    state: 'California',
    latitude: 39.729094,
    longitude: -121.844015,
    city: 'Chico',
    country: 'United States',
  },
  {
    name: 'Towson University',
    state: 'Maryland',
    latitude: 39.39292,
    longitude: -76.604469,
    city: 'Towson',
    country: 'United States',
  },
  {
    name: 'Colorado State University, Fort Collins',
    state: 'Colorado',
    latitude: 40.575891,
    longitude: -105.079947,
    city: 'Fort Collins',
    country: 'United States',
  },
  {
    name: 'University of Cincinnati',
    state: 'Ohio',
    latitude: 39.125645,
    longitude: -84.561384,
    city: 'Cincinnati',
    country: 'United States',
  },
  {
    name: 'St. Olaf College',
    state: 'Minnesota',
    latitude: 44.460376,
    longitude: -93.180324,
    city: 'Northfield',
    country: 'United States',
  },
  {
    name: 'Rochester Institute of Technology',
    state: 'New York',
    latitude: 43.084675,
    longitude: -77.674439,
    city: 'Rochester',
    country: 'United States',
  },
  {
    name: 'Gonzaga University',
    state: 'Washington',
    latitude: 47.66853,
    longitude: -117.403205,
    city: 'Spokane',
    country: 'United States',
  },
  {
    name: 'Western Washington University',
    state: 'Washington',
    latitude: 48.75235,
    longitude: -122.471219,
    city: 'Bellingham',
    country: 'United States',
  },
  {
    name: 'Florida Atlantic University',
    state: 'Florida',
    latitude: 26.35049,
    longitude: -80.089004,
    city: 'Boca Raton',
    country: 'United States',
  },
  {
    name: 'University of Hawaii, Manoa',
    state: 'Hawaii',
    latitude: 21.299373,
    longitude: -157.820047,
    city: 'Honolulu',
    country: 'United States',
  },
  {
    name: 'University of Nebraska, Lincoln',
    state: 'Nebraska',
    latitude: 40.816897,
    longitude: -96.700939,
    city: 'Lincoln',
    country: 'United States',
  },
  {
    name: 'California State University-Monterey Bay',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Marina',
    country: 'United States',
  },
  {
    name: 'Clarkson University',
    state: 'New York',
    latitude: 44.666965,
    longitude: -74.994059,
    city: 'Potsdam',
    country: 'United States',
  },
  {
    name: 'Seattle University',
    state: 'Washington',
    latitude: 47.610502,
    longitude: -122.316778,
    city: 'Seattle',
    country: 'United States',
  },
  {
    name: 'Stevens Institute of Technology',
    state: 'New Jersey',
    latitude: 40.741961,
    longitude: -74.027331,
    city: 'Hoboken',
    country: 'United States',
  },
  {
    name: 'Reed College',
    state: 'Oregon',
    latitude: 45.4792,
    longitude: -122.630383,
    city: 'Portland',
    country: 'United States',
  },
  {
    name: 'Loyola University Chicago',
    state: 'Illinois',
    latitude: 41.998266,
    longitude: -87.657347,
    city: 'Chicago',
    country: 'United States',
  },
  {
    name: 'Manhattan College',
    state: 'New York',
    latitude: 40.900199,
    longitude: -73.906976,
    city: 'Riverdale',
    country: 'United States',
  },
  {
    name: 'California State University, East Bay',
    state: 'California',
    latitude: 37.6561165,
    longitude: -122.0326019,
    city: 'Hayward',
    country: 'United States',
  },
  {
    name: 'University of Mississippi',
    state: 'Mississippi',
    latitude: 34.36997,
    longitude: -89.530204,
    city: 'Lafayette',
    country: 'United States',
  },
  {
    name: 'Chapman University',
    state: 'California',
    latitude: 33.793282,
    longitude: -117.85221,
    city: 'Orange',
    country: 'United States',
  },
  {
    name: 'Virginia Commonwealth University',
    state: 'Virginia',
    latitude: 37.549316,
    longitude: -77.452545,
    city: 'Richmond',
    country: 'United States',
  },
  {
    name: 'Missouri University of Science and Technology',
    state: 'Missouri',
    latitude: 42.1216594,
    longitude: -76.0761959,
    city: 'Rolla',
    country: 'United States',
  },
  {
    name: 'Michigan Technological University',
    state: 'Michigan',
    latitude: 47.119024,
    longitude: -88.551421,
    city: 'Houghton',
    country: 'United States',
  },
  {
    name: 'California State University, Stanislaus',
    state: 'California',
    latitude: 37.5359468,
    longitude: -120.8613785,
    city: 'Turlock',
    country: 'United States',
  },
  {
    name: 'Truman State University',
    state: 'Missouri',
    latitude: 40.19426,
    longitude: -92.571994,
    city: 'Kirksville',
    country: 'United States',
  },
  {
    name: 'Wheaton College (IL)',
    state: 'Illinois',
    latitude: 41.867246,
    longitude: -88.099307,
    city: 'Wheaton',
    country: 'United States',
  },
  {
    name: 'St. Lawrence University',
    state: 'New York',
    latitude: 44.59322,
    longitude: -75.160103,
    city: 'Canton',
    country: 'United States',
  },
  {
    name: 'Miami University (OH)',
    state: 'Ohio',
    latitude: 39.510375,
    longitude: -84.734273,
    city: 'Oxford',
    country: 'United States',
  },
  {
    name: 'University of Rhode Island',
    state: 'Rhode Island',
    latitude: 41.479999,
    longitude: -71.52169,
    city: 'Kingston',
    country: 'United States',
  },
  {
    name: 'Fairfield University',
    state: 'Connecticut',
    latitude: 41.161872,
    longitude: -73.254435,
    city: 'Fairfield',
    country: 'United States',
  },
  {
    name: 'Drake University',
    state: 'Iowa',
    latitude: 41.60037,
    longitude: -93.651109,
    city: 'Des Moines',
    country: 'United States',
  },
  {
    name: 'Oklahoma State University',
    state: 'Oklahoma',
    latitude: 36.11625,
    longitude: -97.058654,
    city: 'Stillwater',
    country: 'United States',
  },
  {
    name: 'Rutgers University, Camden',
    state: 'New Jersey',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Camden',
    country: 'United States',
  },
  {
    name: 'Sonoma State University',
    state: 'California',
    latitude: 38.3437823,
    longitude: -122.7011951,
    city: 'Rohnert Park',
    country: 'United States',
  },
  {
    name: 'Seton Hall University',
    state: 'New Jersey',
    latitude: 40.744626,
    longitude: -74.247373,
    city: 'South Orange',
    country: 'United States',
  },
  {
    name: 'Utah State University',
    state: 'Utah',
    latitude: 41.736185,
    longitude: -111.834849,
    city: 'Logan',
    country: 'United States',
  },
  {
    name: 'SUNY, Geneseo',
    state: 'New York',
    latitude: 42.795726,
    longitude: -77.819422,
    city: 'Geneseo',
    country: 'United States',
  },
  {
    name: "St. John's University (NY)",
    state: 'New York',
    latitude: 40.725631,
    longitude: -73.791681,
    city: 'Queens',
    country: 'United States',
  },
  {
    name: 'California State University-San Marcos',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'San Marcos',
    country: 'United States',
  },
  {
    name: 'University of North Carolina, Charlotte',
    state: 'North Carolina',
    latitude: 35.302717,
    longitude: -80.728955,
    city: 'Charlotte',
    country: 'United States',
  },
  {
    name: 'University of Wisconsin, Eau Claire',
    state: 'Wisconsin',
    latitude: 44.7470586,
    longitude: -91.50150090000001,
    city: 'Eau Claire',
    country: 'United States',
  },
  {
    name: 'Rowan University',
    state: 'New Jersey',
    latitude: 39.707136,
    longitude: -75.114618,
    city: 'Glassboro',
    country: 'United States',
  },
  {
    name: 'Centre College',
    state: 'Kentucky',
    latitude: 37.644992,
    longitude: -84.777508,
    city: 'Danville',
    country: 'United States',
  },
  {
    name: 'California State University, San Bernardino',
    state: 'California',
    latitude: 34.179146,
    longitude: -117.326559,
    city: 'San Bernardino',
    country: 'United States',
  },
  {
    name: "College of Saint Benedict and Saint John's University",
    state: 'Minnesota',
    latitude: 45.58723,
    longitude: -94.366449,
    city: 'Collegeville',
    country: 'United States',
  },
  {
    name: 'Samford University',
    state: 'Alabama',
    latitude: 33.461298,
    longitude: -86.794233,
    city: 'Birmingham',
    country: 'United States',
  },
  {
    name: 'Illinois State University',
    state: 'Illinois',
    latitude: 40.510823,
    longitude: -88.994139,
    city: 'Normal',
    country: 'United States',
  },
  {
    name: 'SUNY Maritime College',
    state: 'New York',
    latitude: 40.80918,
    longitude: -73.80114,
    city: 'Throggs Neck',
    country: 'United States',
  },
  {
    name: 'University of Saint Thomas (MN)',
    state: 'Minnesota',
    latitude: 44.941671,
    longitude: -93.189479,
    city: 'St. Paul',
    country: 'United States',
  },
  {
    name: 'Lewis & Clark College',
    state: 'Oregon',
    latitude: 45.450559,
    longitude: -122.672519,
    city: 'Portland',
    country: 'United States',
  },
  {
    name: 'University of Louisville',
    state: 'Kentucky',
    latitude: 38.215365,
    longitude: -85.762069,
    city: 'Louisville',
    country: 'United States',
  },
  {
    name: 'Providence College',
    state: 'Rhode Island',
    latitude: 41.80893,
    longitude: -71.440179,
    city: 'Providence',
    country: 'United States',
  },
  {
    name: 'Ramapo College of New Jersey',
    state: 'New Jersey',
    latitude: 41.040675,
    longitude: -74.062063,
    city: 'Mahwah',
    country: 'United States',
  },
  {
    name: 'SUNY, College of Environmental Science and Forestry',
    state: 'New York',
    latitude: 43.035448,
    longitude: -76.134621,
    city: 'Syracuse',
    country: 'United States',
  },
  {
    name: 'California State University Maritime Academy',
    state: 'California',
    latitude: 38.069037,
    longitude: -122.229907,
    city: 'Vallejo',
    country: 'United States',
  },
  {
    name: 'Hobart and William Smith Colleges',
    state: 'New York',
    latitude: 42.859377,
    longitude: -76.982284,
    city: 'Geneva',
    country: 'United States',
  },
  {
    name: 'California Lutheran University',
    state: 'California',
    latitude: 34.225578,
    longitude: -118.876899,
    city: 'Thousand Oaks',
    country: 'United States',
  },
  {
    name: 'Salisbury University',
    state: 'Maryland',
    latitude: 38.4001474,
    longitude: -75.632447,
    city: 'Salisbury',
    country: 'United States',
  },
  {
    name: 'University of North Texas',
    state: 'Texas',
    latitude: 33.21151,
    longitude: -97.144841,
    city: 'Denton',
    country: 'United States',
  },
  {
    name: 'University of Mary Washington',
    state: 'Virginia',
    latitude: 38.300082,
    longitude: -77.474999,
    city: 'Fredericksburg',
    country: 'United States',
  },
  {
    name: 'DePaul University',
    state: 'Illinois',
    latitude: 41.878205,
    longitude: -87.627499,
    city: 'Chicago',
    country: 'United States',
  },
  {
    name: 'Thomas Jefferson University',
    state: 'Pennsylvania',
    latitude: 39.95312,
    longitude: -75.169438,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'Kansas State University',
    state: 'Kansas',
    latitude: 39.17881,
    longitude: -96.561834,
    city: 'Manhattan',
    country: 'United States',
  },
  {
    name: 'University of New Hampshire',
    state: 'New Hampshire',
    latitude: 43.134245,
    longitude: -70.924809,
    city: 'Durham',
    country: 'United States',
  },
  {
    name: 'University of Alabama',
    state: 'Alabama',
    latitude: 33.167759,
    longitude: -87.474727,
    city: 'Tuscaloosa',
    country: 'United States',
  },
  {
    name: 'Duquesne University',
    state: 'Pennsylvania',
    latitude: 40.438056,
    longitude: -79.993881,
    city: 'Pittsburgh',
    country: 'United States',
  },
  {
    name: 'Embry-Riddle Aeronautical University, Daytona Beach',
    state: 'Florida',
    latitude: 29.189205,
    longitude: -81.045532,
    city: 'Daytona Beach',
    country: 'United States',
  },
  {
    name: 'Pace University',
    state: 'New York',
    latitude: 40.711649,
    longitude: -74.005783,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'University at Albany, SUNY',
    state: 'New York',
    latitude: 42.689856,
    longitude: -73.820717,
    city: 'Albany',
    country: 'United States',
  },
  {
    name: 'Wofford College',
    state: 'South Carolina',
    latitude: 34.957503,
    longitude: -81.93772,
    city: 'Spartanburg',
    country: 'United States',
  },
  {
    name: 'Ithaca College',
    state: 'New York',
    latitude: 42.42141,
    longitude: -76.501161,
    city: 'Ithaca',
    country: 'United States',
  },
  {
    name: 'Montclair State University',
    state: 'New Jersey',
    latitude: 40.856351,
    longitude: -74.194948,
    city: 'Montclair',
    country: 'United States',
  },
  {
    name: 'College of Charleston',
    state: 'South Carolina',
    latitude: 32.783318,
    longitude: -79.936957,
    city: 'Charleston',
    country: 'United States',
  },
  {
    name: 'Sewanee\u2014University of the South',
    state: 'Tennessee',
    latitude: 35.20443,
    longitude: -85.920942,
    city: 'Sewanee',
    country: 'United States',
  },
  {
    name: 'Butler University',
    state: 'Indiana',
    latitude: 39.839459,
    longitude: -86.168957,
    city: 'Indianapolis',
    country: 'United States',
  },
  {
    name: 'New Mexico Institute of Mining and Technology',
    state: 'New Mexico',
    latitude: 34.065241,
    longitude: -106.903439,
    city: 'Socorro',
    country: 'United States',
  },
  {
    name: 'Hope College',
    state: 'Michigan',
    latitude: 42.78853,
    longitude: -86.103686,
    city: 'Holland',
    country: 'United States',
  },
  {
    name: 'College of Wooster',
    state: 'Ohio',
    latitude: 40.811266,
    longitude: -81.934321,
    city: 'Wooster',
    country: 'United States',
  },
  {
    name: 'Gustavus Adolphus College',
    state: 'Minnesota',
    latitude: 44.322102,
    longitude: -93.968593,
    city: 'St. Peter',
    country: 'United States',
  },
  {
    name: 'SUNY, Farmingdale State College',
    state: 'New York',
    latitude: 40.7245083,
    longitude: -73.4298073,
    city: 'Farmingdale',
    country: 'United States',
  },
  {
    name: 'University of Colorado, Denver',
    state: 'Colorado',
    latitude: 39.74001,
    longitude: -104.992259,
    city: 'Denver',
    country: 'United States',
  },
  {
    name: 'Rockhurst University',
    state: 'Missouri',
    latitude: 39.03268,
    longitude: -94.573356,
    city: 'Kansas City',
    country: 'United States',
  },
  {
    name: 'University of North Florida',
    state: 'Florida',
    latitude: 30.272364,
    longitude: -81.507054,
    city: 'Jacksonville',
    country: 'United States',
  },
  {
    name: "Saint Mary's College of California",
    state: 'California',
    latitude: 37.843851,
    longitude: -122.112331,
    city: 'Moraga',
    country: 'United States',
  },
  {
    name: 'CUNY, Lehman College',
    state: 'New York',
    latitude: 40.8687887,
    longitude: -73.8977693,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Loyola University Maryland',
    state: 'Maryland',
    latitude: 39.345494,
    longitude: -76.622119,
    city: 'Baltimore',
    country: 'United States',
  },
  {
    name: 'CUNY, John Jay College of Criminal Justice',
    state: 'New York',
    latitude: 40.765394,
    longitude: -73.985696,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'New School',
    state: 'New York',
    latitude: 40.73552,
    longitude: -73.996628,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Appalachian State University',
    state: 'North Carolina',
    latitude: 36.220364,
    longitude: -81.686965,
    city: 'Boone',
    country: 'United States',
  },
  {
    name: 'University of Houston, Clear Lake',
    state: 'Texas',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Houston',
    country: 'United States',
  },
  {
    name: 'University of Nevada, Las Vegas',
    state: 'Nevada',
    latitude: 36.107689,
    longitude: -115.137488,
    city: 'Las Vegas',
    country: 'United States',
  },
  {
    name: 'Wabash College',
    state: 'Indiana',
    latitude: 40.034208,
    longitude: -86.904911,
    city: 'Crawfordsville',
    country: 'United States',
  },
  {
    name: 'Mississippi State University',
    state: 'Mississippi',
    latitude: 32.58507,
    longitude: -89.873745,
    city: 'Mississippi State',
    country: 'United States',
  },
  {
    name: 'California State University, Channel Islands',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Camarillo',
    country: 'United States',
  },
  {
    name: 'University of Texas, Arlington',
    state: 'Texas',
    latitude: 32.728388,
    longitude: -97.115142,
    city: 'Arlington',
    country: 'United States',
  },
  {
    name: 'California State University-Dominguez Hills',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Dominguez Hills',
    country: 'United States',
  },
  {
    name: 'University of California-Merced',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Merced',
    country: 'United States',
  },
  {
    name: 'Willamette University',
    state: 'Oregon',
    latitude: 44.93794,
    longitude: -123.030868,
    city: 'Salem',
    country: 'United States',
  },
  {
    name: 'University of Massachusetts Boston',
    state: 'Massachusetts',
    latitude: 42.316001,
    longitude: -71.04793,
    city: 'Boston',
    country: 'United States',
  },
  {
    name: 'Hofstra University',
    state: 'New York',
    latitude: 40.70991,
    longitude: -73.622794,
    city: 'Hempstead',
    country: 'United States',
  },
  {
    name: "Saint Joseph's University (PA)",
    state: 'Pennsylvania',
    latitude: 39.99524,
    longitude: -75.239149,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'Ohio Northern University',
    state: 'Ohio',
    latitude: 40.766277,
    longitude: -83.823217,
    city: 'Ada',
    country: 'United States',
  },
  {
    name: 'Clark University (MA)',
    state: 'Massachusetts',
    latitude: 42.250004,
    longitude: -71.822652,
    city: 'Worcester',
    country: 'United States',
  },
  {
    name: 'Bradley University',
    state: 'Illinois',
    latitude: 40.696379,
    longitude: -89.61616,
    city: 'Peoria',
    country: 'United States',
  },
  {
    name: 'Le Moyne College',
    state: 'New York',
    latitude: 43.047214,
    longitude: -76.088184,
    city: 'Syracuse',
    country: 'United States',
  },
  {
    name: 'Azusa Pacific University',
    state: 'California',
    latitude: 34.13361,
    longitude: -117.905879,
    city: 'Azusa',
    country: 'United States',
  },
  {
    name: 'University of Puerto Rico, Mayaguez',
    state: 'Puerto Rico',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Mayag\u0178ez',
    country: 'United States',
  },
  {
    name: 'Kettering University',
    state: 'Michigan',
    latitude: 43.01075,
    longitude: -83.686029,
    city: 'Flint',
    country: 'United States',
  },
  {
    name: 'University of Puget Sound',
    state: 'Washington',
    latitude: 47.261926,
    longitude: -122.481036,
    city: 'Tacoma',
    country: 'United States',
  },
  {
    name: 'Southwestern University',
    state: 'Texas',
    latitude: 30.633359,
    longitude: -97.667897,
    city: 'Georgetown',
    country: 'United States',
  },
  {
    name: 'Pennsylvania State University',
    state: 'Pennsylvania',
    latitude: 40.807074,
    longitude: -77.85878,
    city: 'State College',
    country: 'United States',
  },
  {
    name: 'Calvin University',
    state: 'Michigan',
    latitude: 42.926939,
    longitude: -85.589237,
    city: 'Grand Rapids',
    country: 'United States',
  },
  {
    name: 'University of Florida, Online',
    state: 'Florida',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Gainesville',
    country: 'United States',
  },
  {
    name: 'University of Alabama at Birmingham',
    state: 'Alabama',
    latitude: 33.506914,
    longitude: -86.80916,
    city: 'Birmingham',
    country: 'United States',
  },
  {
    name: 'California State University-Bakersfield',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Bakersfield',
    country: 'United States',
  },
  {
    name: 'Lake Forest College',
    state: 'Illinois',
    latitude: 42.249995,
    longitude: -87.830785,
    city: 'Lake Forest',
    country: 'United States',
  },
  {
    name: 'University of Minnesota, Morris',
    state: 'Minnesota',
    latitude: 45.589457,
    longitude: -95.904411,
    city: 'Morris',
    country: 'United States',
  },
  {
    name: 'University of North Dakota',
    state: 'North Dakota',
    latitude: 47.921734,
    longitude: -97.070896,
    city: 'Grand Forks',
    country: 'United States',
  },
  {
    name: 'Tennessee Technological University',
    state: 'Tennessee',
    latitude: 36.1628,
    longitude: 85.5016,
    city: 'Cookeville',
    country: 'United States',
  },
  {
    name: 'Valparaiso University',
    state: 'Indiana',
    latitude: 41.462983,
    longitude: -87.03985,
    city: 'Valparaiso',
    country: 'United States',
  },
  {
    name: 'Embry-Riddle Aeronautical University, Prescott',
    state: 'Arizona',
    latitude: 34.541425,
    longitude: -112.468729,
    city: 'Prescott',
    country: 'United States',
  },
  {
    name: 'Grove City College',
    state: 'Pennsylvania',
    latitude: 41.155397,
    longitude: -80.081529,
    city: 'Grove City',
    country: 'United States',
  },
  {
    name: 'Marist College',
    state: 'New York',
    latitude: 41.722925,
    longitude: -73.931864,
    city: 'Poughkeepsie',
    country: 'United States',
  },
  {
    name: 'Northeastern University Lifelong Learning Network',
    state: 'Massachusetts',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Boston',
    country: 'United States',
  },
  {
    name: 'SUNY, College at New Paltz',
    state: 'New York',
    latitude: 41.7318899,
    longitude: -74.10050439999999,
    city: 'New Paltz',
    country: 'United States',
  },
  {
    name: 'University of Nebraska, Omaha',
    state: 'Nebraska',
    latitude: 41.259612,
    longitude: -96.005275,
    city: 'Omaha',
    country: 'United States',
  },
  {
    name: 'The Catholic University of America',
    state: 'District of Columbia',
    latitude: 38.932673,
    longitude: -76.997462,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'West Virginia University',
    state: 'West Virginia',
    latitude: 39.51306,
    longitude: -79.875079,
    city: 'Morgantown',
    country: 'United States',
  },
  {
    name: 'University of Alabama in Huntsville',
    state: 'Alabama',
    latitude: 34.723197,
    longitude: -86.644098,
    city: 'Huntsville',
    country: 'United States',
  },
  {
    name: 'Juniata College',
    state: 'Pennsylvania',
    latitude: 40.500042,
    longitude: -78.017553,
    city: 'Huntingdon',
    country: 'United States',
  },
  {
    name: 'University of Idaho',
    state: 'Idaho',
    latitude: 46.820755,
    longitude: -117.039767,
    city: 'Moscow',
    country: 'United States',
  },
  {
    name: 'Lawrence University',
    state: 'Wisconsin',
    latitude: 44.26178,
    longitude: -88.416564,
    city: 'Appleton',
    country: 'United States',
  },
  {
    name: 'University of Michigan-Dearborn',
    state: 'Michigan',
    latitude: 42.313764,
    longitude: -83.21127,
    city: 'Dearborn',
    country: 'United States',
  },
  {
    name: 'John Carroll University',
    state: 'Ohio',
    latitude: 41.487306,
    longitude: -81.535278,
    city: 'University Heights',
    country: 'United States',
  },
  {
    name: 'University of Missouri, Saint Louis',
    state: 'Missouri',
    latitude: 38.708587,
    longitude: -90.311021,
    city: 'St. Louis',
    country: 'United States',
  },
  {
    name: 'Maine Maritime Academy',
    state: 'Maine',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Castine',
    country: 'United States',
  },
  {
    name: 'Howard University',
    state: 'District of Columbia',
    latitude: 38.922704,
    longitude: -77.021124,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'Muhlenberg College',
    state: 'Pennsylvania',
    latitude: 40.596767,
    longitude: -75.50877,
    city: 'Allentown',
    country: 'United States',
  },
  {
    name: 'University of Wyoming',
    state: 'Wyoming',
    latitude: 41.312441,
    longitude: -105.585683,
    city: 'Laramie',
    country: 'United States',
  },
  {
    name: 'University of Massachusetts Lowell',
    state: 'Massachusetts',
    latitude: 42.652679,
    longitude: -71.325414,
    city: 'Lowell',
    country: 'United States',
  },
  {
    name: 'Brigham Young University-Idaho',
    state: 'Idaho',
    latitude: 43.814603,
    longitude: -111.783809,
    city: 'Rexburg',
    country: 'United States',
  },
  {
    name: 'Mercer University',
    state: 'Georgia',
    latitude: 32.832176,
    longitude: -83.647993,
    city: 'Macon',
    country: 'United States',
  },
  {
    name: 'Montana Tech of the University of Montana',
    state: 'Montana',
    latitude: 46.012343,
    longitude: -112.556797,
    city: 'Butte',
    country: 'United States',
  },
  {
    name: 'Beloit College',
    state: 'Wisconsin',
    latitude: 42.503079,
    longitude: -89.029593,
    city: 'Beloit',
    country: 'United States',
  },
  {
    name: 'University of St. Thomas (TX)',
    state: 'Texas',
    latitude: 29.787546,
    longitude: -95.617627,
    city: 'Houston',
    country: 'United States',
  },
  {
    name: 'Washington & Jefferson College',
    state: 'Pennsylvania',
    latitude: 40.170634,
    longitude: -80.240975,
    city: 'Washington',
    country: 'United States',
  },
  {
    name: 'Austin College',
    state: 'Texas',
    latitude: 33.647852,
    longitude: -96.595009,
    city: 'Sherman',
    country: 'United States',
  },
  {
    name: 'SUNY Polytechnic Institute',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Utica',
    country: 'United States',
  },
  {
    name: 'University of Wisconsin, La Crosse',
    state: 'Wisconsin',
    latitude: 43.812625,
    longitude: -91.251919,
    city: 'La Crosse',
    country: 'United States',
  },
  {
    name: 'Portland State University',
    state: 'Oregon',
    latitude: 45.511668,
    longitude: -122.683762,
    city: 'Portland',
    country: 'United States',
  },
  {
    name: 'Loma Linda University',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Loma Linda',
    country: 'United States',
  },
  {
    name: 'Milwaukee School of Engineering',
    state: 'Wisconsin',
    latitude: 43.043935,
    longitude: -87.908389,
    city: 'Milwaukee',
    country: 'United States',
  },
  {
    name: 'North Dakota State University',
    state: 'North Dakota',
    latitude: 46.891774,
    longitude: -96.799994,
    city: 'Fargo',
    country: 'United States',
  },
  {
    name: 'University of Minnesota, Duluth',
    state: 'Minnesota',
    latitude: 46.787965,
    longitude: -92.099849,
    city: 'Duluth',
    country: 'United States',
  },
  {
    name: 'Georgia State University',
    state: 'Georgia',
    latitude: 33.62977,
    longitude: -84.552899,
    city: 'Atlanta',
    country: 'United States',
  },
  {
    name: 'Adelphi University',
    state: 'New York',
    latitude: 40.72605,
    longitude: -73.636909,
    city: 'Garden City',
    country: 'United States',
  },
  {
    name: 'Bryant University',
    state: 'Rhode Island',
    latitude: 41.9209914,
    longitude: -71.5368981,
    city: 'Smithfield',
    country: 'United States',
  },
  {
    name: 'University of Dallas',
    state: 'Texas',
    latitude: 32.844365,
    longitude: -96.920713,
    city: 'Irving',
    country: 'United States',
  },
  {
    name: 'West Chester University of Pennsylvania',
    state: 'Pennsylvania',
    latitude: 39.95063,
    longitude: -75.59882,
    city: 'West Chester',
    country: 'United States',
  },
  {
    name: 'Westminster College (UT)',
    state: 'Utah',
    latitude: 40.769112,
    longitude: -111.890981,
    city: 'Salt Lake City',
    country: 'United States',
  },
  {
    name: 'Cedarville University',
    state: 'Ohio',
    latitude: 39.747368,
    longitude: -83.808823,
    city: 'Cedarville',
    country: 'United States',
  },
  {
    name: 'Pacific Lutheran University',
    state: 'Washington',
    latitude: 47.145802,
    longitude: -122.439751,
    city: 'Tacoma',
    country: 'United States',
  },
  {
    name: 'Indiana University-Purdue University, Indianapolis',
    state: 'Indiana',
    latitude: 39.773665,
    longitude: -86.175583,
    city: 'Indianapolis',
    country: 'United States',
  },
  {
    name: 'University of Redlands',
    state: 'California',
    latitude: 34.055282,
    longitude: -117.18258,
    city: 'Redlands',
    country: 'United States',
  },
  {
    name: 'Oregon Institute of Technology',
    state: 'Oregon',
    latitude: 42.254163,
    longitude: -121.782036,
    city: 'Klamath Falls',
    country: 'United States',
  },
  {
    name: 'Seattle Pacific University',
    state: 'Washington',
    latitude: 47.649689,
    longitude: -122.360907,
    city: 'Seattle',
    country: 'United States',
  },
  {
    name: 'College of Saint Benedict',
    state: 'Minnesota',
    latitude: 45.563353,
    longitude: -94.317354,
    city: 'St. Joseph',
    country: 'United States',
  },
  {
    name: 'University of Missouri-Kansas City',
    state: 'Missouri',
    latitude: 39.034305,
    longitude: -94.575708,
    city: 'Kansas City',
    country: 'United States',
  },
  {
    name: 'Virginia Military Institute',
    state: 'Virginia',
    latitude: 37.788935,
    longitude: -79.439622,
    city: 'Lexington',
    country: 'United States',
  },
  {
    name: 'Northern Arizona University',
    state: 'Arizona',
    latitude: 35.2447,
    longitude: -111.502179,
    city: 'Flagstaff',
    country: 'United States',
  },
  {
    name: 'Wagner College',
    state: 'New York',
    latitude: 40.6274394,
    longitude: -74.0946311,
    city: 'Staten Island',
    country: 'United States',
  },
  {
    name: 'Rollins College',
    state: 'Florida',
    latitude: 28.594574,
    longitude: -81.350716,
    city: 'Winter Park',
    country: 'United States',
  },
  {
    name: 'Texas State University',
    state: 'Texas',
    latitude: 29.885985,
    longitude: -97.941968,
    city: 'San Marcos',
    country: 'United States',
  },
  {
    name: 'McDaniel College',
    state: 'Maryland',
    latitude: 39.574725,
    longitude: -76.99458,
    city: 'Westminster',
    country: 'United States',
  },
  {
    name: 'Simmons University',
    state: 'Massachusetts',
    latitude: 42.339181,
    longitude: -71.099145,
    city: 'Boston',
    country: 'United States',
  },
  {
    name: 'Hampden-Sydney College',
    state: 'Virginia',
    latitude: 37.247462,
    longitude: -78.45683,
    city: 'Hampden-Sydney',
    country: 'United States',
  },
  {
    name: 'Linfield University',
    state: 'Oregon',
    latitude: 45.202211,
    longitude: -123.202111,
    city: 'McMinnville',
    country: 'United States',
  },
  {
    name: 'Saint Anselm College',
    state: 'New Hampshire',
    latitude: 42.987702,
    longitude: -71.508032,
    city: 'Manchester',
    country: 'United States',
  },
  {
    name: 'University of Texas at San Antonio',
    state: 'Texas',
    latitude: 29.585178,
    longitude: -98.61727,
    city: 'San Antonio',
    country: 'United States',
  },
  {
    name: 'Siena College',
    state: 'New York',
    latitude: 42.715685,
    longitude: -73.755341,
    city: 'Loudonville',
    country: 'United States',
  },
  {
    name: 'University of North Carolina, Wilmington',
    state: 'North Carolina',
    latitude: 34.226953,
    longitude: -77.879387,
    city: 'Wilmington',
    country: 'United States',
  },
  {
    name: 'SUNY College at Old Westbury',
    state: 'New York',
    latitude: 40.781238,
    longitude: -73.600305,
    city: 'Old Westbury',
    country: 'United States',
  },
  {
    name: "Texas Woman's University",
    state: 'Texas',
    latitude: 33.226373,
    longitude: -97.128539,
    city: 'Denton',
    country: 'United States',
  },
  {
    name: 'Fairleigh Dickinson University',
    state: 'New Jersey',
    latitude: 40.886875,
    longitude: -74.019444,
    city: 'Teaneck',
    country: 'United States',
  },
  {
    name: 'Florida Gulf Coast University',
    state: 'Florida',
    latitude: 26.640845,
    longitude: -81.868194,
    city: 'Fort Myers',
    country: 'United States',
  },
  {
    name: 'Massachusetts Maritime Academy',
    state: 'Massachusetts',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Buzzards Bay',
    country: 'United States',
  },
  {
    name: 'Oakland University',
    state: 'Michigan',
    latitude: 42.672571,
    longitude: -83.218961,
    city: 'Rochester',
    country: 'United States',
  },
  {
    name: 'Quinnipiac University',
    state: 'Connecticut',
    latitude: 41.421607,
    longitude: -72.89476,
    city: 'Hamden',
    country: 'United States',
  },
  {
    name: 'Stonehill College',
    state: 'Massachusetts',
    latitude: 42.060149,
    longitude: -71.086754,
    city: 'Easton',
    country: 'United States',
  },
  {
    name: 'Pratt Institute',
    state: 'New York',
    latitude: 40.690548,
    longitude: -73.968304,
    city: 'Brooklyn',
    country: 'United States',
  },
  {
    name: 'Allegheny College',
    state: 'Pennsylvania',
    latitude: 41.647872,
    longitude: -80.146133,
    city: 'Meadville',
    country: 'United States',
  },
  {
    name: 'Canisius College',
    state: 'New York',
    latitude: 42.925497,
    longitude: -78.853743,
    city: 'Buffalo',
    country: 'United States',
  },
  {
    name: 'New College of Florida',
    state: 'Florida',
    latitude: 27.384731,
    longitude: -82.559104,
    city: 'Sarasota',
    country: 'United States',
  },
  {
    name: 'Ohio University',
    state: 'Ohio',
    latitude: 39.328502,
    longitude: -82.10444,
    city: 'Athens',
    country: 'United States',
  },
  {
    name: 'Illinois Wesleyan University',
    state: 'Illinois',
    latitude: 40.49491,
    longitude: -88.930519,
    city: 'Bloomington',
    country: 'United States',
  },
  {
    name: 'Drew University',
    state: 'New Jersey',
    latitude: 40.762575,
    longitude: -74.42134,
    city: 'Madison',
    country: 'United States',
  },
  {
    name: 'University of Detroit Mercy',
    state: 'Michigan',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Detroit',
    country: 'United States',
  },
  {
    name: 'Central Washington University',
    state: 'Washington',
    latitude: 47.001244,
    longitude: -120.543144,
    city: 'Ellensburg',
    country: 'United States',
  },
  {
    name: 'New York Institute of Technology',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Old Westbury',
    country: 'United States',
  },
  {
    name: 'Monmouth University',
    state: 'New Jersey',
    latitude: 0.0,
    longitude: 0.0,
    city: 'West Long Branch',
    country: 'United States',
  },
  {
    name: 'University of Texas, El Paso',
    state: 'Texas',
    latitude: 31.770526,
    longitude: -106.504291,
    city: 'El Paso',
    country: 'United States',
  },
  {
    name: 'University of Scranton',
    state: 'Pennsylvania',
    latitude: 41.406833,
    longitude: -75.658715,
    city: 'Scranton',
    country: 'United States',
  },
  {
    name: 'Point Loma Nazarene University',
    state: 'California',
    latitude: 32.896859,
    longitude: -117.196231,
    city: 'San Diego',
    country: 'United States',
  },
  {
    name: 'University of Baltimore',
    state: 'Maryland',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Baltimore',
    country: 'United States',
  },
  {
    name: 'Iona College',
    state: 'New York',
    latitude: 40.925856,
    longitude: -73.788655,
    city: 'New Rochelle',
    country: 'United States',
  },
  {
    name: 'Dominican University of California',
    state: 'California',
    latitude: 0.0,
    longitude: 0.0,
    city: 'San Rafael',
    country: 'United States',
  },
  {
    name: "Saint Peter's University",
    state: 'New Jersey',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Jersey City',
    country: 'United States',
  },
  {
    name: 'Susquehanna University',
    state: 'Pennsylvania',
    latitude: 40.799591,
    longitude: -76.870163,
    city: 'Selinsgrove',
    country: 'United States',
  },
  {
    name: 'Molloy College',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Rockville Centre',
    country: 'United States',
  },
  {
    name: 'Christopher Newport University',
    state: 'Virginia',
    latitude: 37.065077,
    longitude: -76.493257,
    city: 'Newport News',
    country: 'United States',
  },
  {
    name: 'Taylor University',
    state: 'Indiana',
    latitude: 40.459153,
    longitude: -85.496728,
    city: 'Upland',
    country: 'United States',
  },
  {
    name: 'University of Texas, Rio Grande Valley',
    state: 'Texas',
    latitude: 26.30324,
    longitude: -98.174689,
    city: 'Edinburg',
    country: 'United States',
  },
  {
    name: 'Grand Valley State University',
    state: 'Michigan',
    latitude: 42.961423,
    longitude: -85.888807,
    city: 'Allendale',
    country: 'United States',
  },
  {
    name: 'Ball State University',
    state: 'Indiana',
    latitude: 40.197647,
    longitude: -85.409484,
    city: 'Muncie',
    country: 'United States',
  },
  {
    name: 'Montana State University',
    state: 'Montana',
    latitude: 45.679325,
    longitude: -111.033184,
    city: 'Bozeman',
    country: 'United States',
  },
  {
    name: 'Lewis University',
    state: 'Illinois',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Romeoville',
    country: 'United States',
  },
  {
    name: 'Principia College',
    state: 'Illinois',
    latitude: 38.955606,
    longitude: -90.347431,
    city: 'Elsah',
    country: 'United States',
  },
  {
    name: 'Kennesaw State University',
    state: 'Georgia',
    latitude: 34.0041089,
    longitude: -84.6583745,
    city: 'Kennesaw',
    country: 'United States',
  },
  {
    name: 'East Carolina University',
    state: 'North Carolina',
    latitude: 35.61106,
    longitude: -77.372499,
    city: 'Greenville',
    country: 'United States',
  },
  {
    name: 'University of New Mexico',
    state: 'New Mexico',
    latitude: 35.08418,
    longitude: -106.648639,
    city: 'Albuquerque',
    country: 'United States',
  },
  {
    name: 'Menlo College',
    state: 'California',
    latitude: 37.462488,
    longitude: -122.197799,
    city: 'Atherton',
    country: 'United States',
  },
  {
    name: 'Augustana College',
    state: 'Illinois',
    latitude: 41.505249,
    longitude: -90.547656,
    city: 'Rock Island',
    country: 'United States',
  },
  {
    name: 'La Salle University',
    state: 'Pennsylvania',
    latitude: 40.039295,
    longitude: -75.152967,
    city: 'Philadelphia',
    country: 'United States',
  },
  {
    name: 'Albion College',
    state: 'Michigan',
    latitude: 42.243776,
    longitude: -84.745039,
    city: 'Albion',
    country: 'United States',
  },
  {
    name: 'Louisiana Tech University',
    state: 'Louisiana',
    latitude: 32.530501,
    longitude: -92.639789,
    city: 'Ruston',
    country: 'United States',
  },
  {
    name: "St. Edward's University",
    state: 'Texas',
    latitude: 30.232525,
    longitude: -97.758441,
    city: 'Austin',
    country: 'United States',
  },
  {
    name: 'Norwich University',
    state: 'Vermont',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Northfield',
    country: 'United States',
  },
  {
    name: 'CUNY, College of Staten Island',
    state: 'New York',
    latitude: 40.5952146,
    longitude: -74.1827119,
    city: 'Staten Island',
    country: 'United States',
  },
  {
    name: 'Berea College',
    state: 'Kentucky',
    latitude: 37.570189,
    longitude: -84.29296,
    city: 'Berea',
    country: 'United States',
  },
  {
    name: 'Central Connecticut State University',
    state: 'Connecticut',
    latitude: 0.0,
    longitude: 0.0,
    city: 'New Britain',
    country: 'United States',
  },
  {
    name: 'Stockton University',
    state: 'New Jersey',
    latitude: 39.4728755,
    longitude: -74.4642861,
    city: 'Galloway',
    country: 'United States',
  },
  {
    name: 'SUNY Cortland',
    state: 'New York',
    latitude: 42.607935,
    longitude: -76.18450969999999,
    city: 'Cortland',
    country: 'United States',
  },
  {
    name: 'Hillsdale College',
    state: 'Michigan',
    latitude: 41.931398,
    longitude: -84.633435,
    city: 'Hillsdale',
    country: 'United States',
  },
  {
    name: 'University of North Georgia',
    state: 'Georgia',
    latitude: 34.531943,
    longitude: -83.986084,
    city: 'Dahlonega',
    country: 'United States',
  },
  {
    name: 'Wentworth Institute of Technology',
    state: 'Massachusetts',
    latitude: 42.353213,
    longitude: -71.057876,
    city: 'Boston',
    country: 'United States',
  },
  {
    name: "Mount St. Mary's University (MD)",
    state: 'Maryland',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Emmitsburg',
    country: 'United States',
  },
  {
    name: 'John Brown University',
    state: 'Arkansas',
    latitude: 36.18726,
    longitude: -94.558494,
    city: 'Siloam Springs',
    country: 'United States',
  },
  {
    name: 'Brigham Young University-Hawaii',
    state: 'Hawaii',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Laie',
    country: 'United States',
  },
  {
    name: 'University of Wisconsin-Platteville',
    state: 'Wisconsin',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Platteville',
    country: 'United States',
  },
  {
    name: "St. John's College, Annapolis",
    state: 'Maryland',
    latitude: 38.9767,
    longitude: -76.489934,
    city: 'Annapolis',
    country: 'United States',
  },
  {
    name: 'University of Evansville',
    state: 'Indiana',
    latitude: 37.969957,
    longitude: -87.532332,
    city: 'Evansville',
    country: 'United States',
  },
  {
    name: 'Agnes Scott College',
    state: 'Georgia',
    latitude: 33.770045,
    longitude: -84.295486,
    city: 'Decatur',
    country: 'United States',
  },
  {
    name: 'University of South Dakota',
    state: 'South Dakota',
    latitude: 42.78251,
    longitude: -96.925776,
    city: 'Vermillion',
    country: 'United States',
  },
  {
    name: 'Goucher College',
    state: 'Maryland',
    latitude: 39.409412,
    longitude: -76.600643,
    city: 'Baltimore',
    country: 'United States',
  },
  {
    name: 'Embry-Riddle Aeronautical University, Worldwide',
    state: 'Florida',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Daytona Beach',
    country: 'United States',
  },
  {
    name: 'New Mexico State University',
    state: 'New Mexico',
    latitude: 32.27521,
    longitude: -106.752689,
    city: 'Las Cruces',
    country: 'United States',
  },
  {
    name: 'Wayne State University',
    state: 'Michigan',
    latitude: 42.356791,
    longitude: -83.064949,
    city: 'Detroit',
    country: 'United States',
  },
  {
    name: "St. Mary's College of Maryland",
    state: 'Maryland',
    latitude: 38.817598,
    longitude: -77.268219,
    city: "St. Mary's City",
    country: 'United States',
  },
  {
    name: 'Saint Vincent College',
    state: 'Pennsylvania',
    latitude: 40.291273,
    longitude: -79.400921,
    city: 'Latrobe',
    country: 'United States',
  },
  {
    name: 'University of New Hampshire, Manchester',
    state: 'New Hampshire',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Manchester',
    country: 'United States',
  },
  {
    name: 'Wheaton College (MA)',
    state: 'Massachusetts',
    latitude: 41.968482,
    longitude: -71.185197,
    city: 'Norton',
    country: 'United States',
  },
  {
    name: 'Abilene Christian University',
    state: 'Texas',
    latitude: 32.47982,
    longitude: -99.708039,
    city: 'Abilene',
    country: 'United States',
  },
  {
    name: 'CUNY Graduate School and University Center',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'SUNY, College at Oneonta',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Oneonta',
    country: 'United States',
  },
  {
    name: 'Sarah Lawrence College',
    state: 'New York',
    latitude: 40.9347,
    longitude: -73.843272,
    city: 'Bronxville',
    country: 'United States',
  },
  {
    name: 'Hamline University',
    state: 'Minnesota',
    latitude: 44.966477,
    longitude: -93.165359,
    city: 'Saint Paul',
    country: 'United States',
  },
  {
    name: "Saint Mary's University of Minnesota",
    state: 'Minnesota',
    latitude: 44.045336,
    longitude: -91.673367,
    city: 'Winona',
    country: 'United States',
  },
  {
    name: 'Elizabethtown College',
    state: 'Pennsylvania',
    latitude: 40.148827,
    longitude: -76.595422,
    city: 'Elizabethtown',
    country: 'United States',
  },
  {
    name: 'Christian Brothers University',
    state: 'Tennessee',
    latitude: 35.127647,
    longitude: -89.983803,
    city: 'Memphis',
    country: 'United States',
  },
  {
    name: 'Old Dominion University',
    state: 'Virginia',
    latitude: 36.8889,
    longitude: -76.303,
    city: 'Norfolk',
    country: 'United States',
  },
  {
    name: 'Ohio Wesleyan University',
    state: 'Ohio',
    latitude: 40.295043,
    longitude: -83.068078,
    city: 'Delaware',
    country: 'United States',
  },
  {
    name: 'Ursinus College',
    state: 'Pennsylvania',
    latitude: 40.191492,
    longitude: -75.458534,
    city: 'Collegeville',
    country: 'United States',
  },
  {
    name: 'South Dakota School of Mines and Technology',
    state: 'South Dakota',
    latitude: 44.081165,
    longitude: -103.230889,
    city: 'Rapid City',
    country: 'United States',
  },
  {
    name: "Saint Michael's College",
    state: 'Vermont',
    latitude: 44.49276,
    longitude: -73.165081,
    city: 'Colchester',
    country: 'United States',
  },
  {
    name: 'Lipscomb University',
    state: 'Tennessee',
    latitude: 36.147828,
    longitude: -86.820217,
    city: 'Nashville',
    country: 'United States',
  },
  {
    name: 'St Bonaventure University',
    state: 'New York',
    latitude: 0.0,
    longitude: 0.0,
    city: 'St. Bonaventure',
    country: 'United States',
  },
  {
    name: 'University of Colorado Colorado Springs',
    state: 'Colorado',
    latitude: 38.9043608,
    longitude: -104.7637619,
    city: 'Colorado Springs',
    country: 'United States',
  },
  {
    name: 'Georgia College & State University',
    state: 'Georgia',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Milledgeville',
    country: 'United States',
  },
  {
    name: 'University of Northern Iowa',
    state: 'Iowa',
    latitude: 42.513108,
    longitude: -92.462089,
    city: 'Cedar Falls',
    country: 'United States',
  },
  {
    name: 'University of North Carolina, Greensboro',
    state: 'North Carolina',
    latitude: 36.06653,
    longitude: -79.819819,
    city: 'Greensboro',
    country: 'United States',
  },
  {
    name: 'Marymount University',
    state: 'Virginia',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Arlington',
    country: 'United States',
  },
  {
    name: 'Southern Illinois University Edwardsville',
    state: 'Illinois',
    latitude: 38.8414469,
    longitude: -89.9440061,
    city: 'Edwardsville',
    country: 'United States',
  },
  {
    name: 'Sam Houston State University',
    state: 'Texas',
    latitude: 30.714614,
    longitude: -95.547926,
    city: 'Huntsville',
    country: 'United States',
  },
  {
    name: 'Belmont University',
    state: 'Tennessee',
    latitude: 36.134069,
    longitude: -86.795738,
    city: 'Nashville',
    country: 'United States',
  },
  {
    name: 'SUNY at Purchase College',
    state: 'New York',
    latitude: 41.038553,
    longitude: -73.698075,
    city: 'Purchase',
    country: 'United States',
  },
  {
    name: 'The Juilliard School',
    state: 'New York',
    latitude: 40.755693,
    longitude: -73.975209,
    city: 'New York',
    country: 'United States',
  },
  {
    name: 'Saint Francis University',
    state: 'Pennsylvania',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Loretto',
    country: 'United States',
  },
  {
    name: 'College of Idaho',
    state: 'Idaho',
    latitude: 43.654855,
    longitude: -116.675961,
    city: 'Caldwell',
    country: 'United States',
  },
  {
    name: 'Loyola University New Orleans',
    state: 'Louisiana',
    latitude: 29.95369,
    longitude: -90.077714,
    city: 'New Orleans',
    country: 'United States',
  },
  {
    name: 'Xavier University',
    state: 'Ohio',
    latitude: 39.149037,
    longitude: -84.476379,
    city: 'Cincinnati',
    country: 'United States',
  },
  {
    name: 'The University of Texas of the Permian Basin',
    state: 'Texas',
    latitude: 31.84915,
    longitude: -102.375189,
    city: 'Odessa',
    country: 'United States',
  },
  {
    name: "St. Joseph's College (NY)",
    state: 'New York',
    latitude: 40.690548,
    longitude: -73.968304,
    city: 'Brooklyn',
    country: 'United States',
  },
  {
    name: 'Moravian University',
    state: 'Pennsylvania',
    latitude: 40.630303,
    longitude: -75.381596,
    city: 'Bethlehem',
    country: 'United States',
  },
  {
    name: 'Lawrence Technological University',
    state: 'Michigan',
    latitude: 42.450606,
    longitude: -83.278458,
    city: 'Southfield',
    country: 'United States',
  },
  {
    name: "Saint Martin's University",
    state: 'Washington',
    latitude: 0.0,
    longitude: 0.0,
    city: 'Lacey',
    country: 'United States',
  },
  {
    name: 'University of Memphis',
    state: 'Tennessee',
    latitude: 35.118453,
    longitude: -89.939618,
    city: 'Memphis',
    country: 'United States',
  },
];

export const programTypes = [
  "Master's",
  'Ph.D.',
  'J.D.', // Law degree
  'M.D.', // Medical degree
  'M.B.A.', // Business degree
  'Ed.D.', // Doctor of Education
  'M.P.H.', // Master of Public Health
  'Professional Certificate',
  'Postdoctoral Fellowship',
  'Residency Program',
  "Associate's Degree",
  'Trade School / Vocational',
  'Gap Year',
  'Undecided',
  'Other',
];

export const disciplines = [
  'Accounting',
  'Anthropology',
  'Architecture',
  'Art History',
  'Biology',
  'Business Administration',
  'Chemistry',
  'Civil Engineering',
  'Communication',
  'Computer Engineering',
  'Computer Science',
  'Creative Writing',
  'Criminal Justice',
  'Data Science',
  'Dentistry',
  'Design',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English Literature',
  'Environmental Science',
  'Finance',
  'Fine Arts',
  'History',
  'International Relations',
  'Journalism',
  'Law',
  'Management',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Music',
  'Nursing',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Statistics',
  'Theology',
  'Urban Planning',
];
